### ISSUE TITLE
App crashes on clicking the login button in the SplashActivity

### ISSUE THREAD

**Issue by mkmar01** [coding-blocks/CodeQuizAndroid#1]

**Comment by batbrain7** [comment]
![ezgif com-video-to-gif-4](https://cloud.githubusercontent.com/assets/16780496/26580969/12080cda-4558-11e7-8cce-a0fee726b92b.gif)

**Comment by piyush0** [comment]
Add a progress dialog to show the loading of data from backend, if no backend is connectivity is there, show a toast showing server error

**Comment by mkmar01** [comment]
Definitely

**Comment by piyush0** [comment]
Solved by @batbrain7 in #2
